# https://taskfile.dev
version: '3'

vars:
  WORKSPACE_DIR: "workspace"

tasks:
  fix:
    desc: Fix Terraform formatting
    cmds:
      - task: terraform-command
        vars: { TF_COMMAND: "fmt -recursive -write=true", TF_CMD_DIR: "{{.ROOT_DIR}}" }

  lint:
    desc: Formatting and linting
    cmds:
      - task: terraform-validate
      - task: terraform-format-check

  plan:
    desc: Run "terraform plan" in "{{.WORKSPACE_DIR}}"
    requires:
      vars: [OPSLEVEL_API_TOKEN]
    cmds:
      - task: init-and-plan

  apply:
    desc: Run "terraform apply" in "{{.WORKSPACE_DIR}}"
    requires:
      vars: [OPSLEVEL_API_TOKEN]
    cmds:
      - task: init-and-apply

  apply-demo:
    desc: Run "terraform apply" to generate a demo account
    requires:
      vars: [OPSLEVEL_API_TOKEN, SANDBOX_USER_EMAIL]
    env:
      TF_VAR_account_token:
        sh: echo "$OPSLEVEL_API_TOKEN"
      TF_VAR_user_email:
        sh: echo "$SANDBOX_USER_EMAIL"
    cmds:
      - task: install-terraform
      - "terraform -chdir={{.WORKSPACE_DIR}} init --upgrade"
      - "terraform -chdir={{.WORKSPACE_DIR}} apply {{.CLI_ARGS}}"

  destroy:
    desc: Run "terraform destroy" in "{{.WORKSPACE_DIR}}"
    requires:
      vars: [OPSLEVEL_API_TOKEN]
    cmds:
      - task: init-and-destroy

  factory-reset:
    desc: Run script to destroy all resources in account
    requires:
      vars: [OPSLEVEL_API_TOKEN]
    vars:
      ACCOUNT_NAME:
        sh: opslevel graphql -q='query { account { name }}' | jq -r '.[0].account.name'
    cmds:
      - echo "Destroying all resources in account '{{.ACCOUNT_NAME}}'..."
      - ./clear_account.sh
    prompt: "Are you sure you want to destroy all resources in account '{{.ACCOUNT_NAME}}'?"

  init-and-*:
    internal: true
    desc: Run "terraform init -upgrade" in "{{.WORKSPACE_DIR}}" then '{{index .MATCH 0}}'
    cmds:
      - task: terraform-command
        vars: { TF_COMMAND: 'init -upgrade', TF_CMD_DIR: "{{.WORKSPACE_DIR}}" }
      - task: terraform-command
        vars: { TF_COMMAND: '{{index .MATCH 0}}', TF_CMD_DIR: "{{.WORKSPACE_DIR}}" }

  terraform-validate:
    internal: true
    cmds:
      - task: terraform-command
        vars: { TF_COMMAND: "validate -no-tests", TF_CMD_DIR: "{{.ROOT_DIR}}" }

  terraform-format-check:
    internal: true
    cmds:
      - cmd: echo "Listing all terraform files that need formatting..."
      - task: terraform-command
        vars: { TF_COMMAND: "fmt -recursive -check", TF_CMD_DIR: "{{.ROOT_DIR}}" }

  terraform-command:
    internal: true
    requires:
      vars: [TF_COMMAND, TF_CMD_DIR]
    preconditions:
      - sh: 'which terraform'
        msg: '"terraform" needed - run "brew install terraform"'
    cmds:
      - task: install-terraform
      - "terraform -chdir={{.TF_CMD_DIR}} {{.TF_COMMAND}} {{.CLI_ARGS}}"

  install-terraform:
    internal: true
    platforms: [darwin]
    preconditions:
      - sh: 'which brew'
        msg: '"brew" needed to install terraform - see https://brew.sh'
    status:
      - test -n "command -v terraform"
    cmds:
      - echo "Installing terraform..."
      - brew tap hashicorp/tap
      - brew install hashicorp/tap/terraform
