name: "Custom Actions Handler"

on:
  repository_dispatch:
    types:
      - actions

jobs:
  handler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.1"
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup OpsLevel CLI
        uses: opslevel/actions/setup-cli@v1
      - name: Apply
        env:
          OPSLEVEL_API_TOKEN: ${{ toJson(github.event.client_payload.api_token) }}
          SANDBOX_USER_EMAIL: ${{ toJson(github.event.client_payload.user_email) }}
        run: |
          task factory-reset -y
          task apply-demo -- -auto-approve
